Added test1.1
EmirVildanov/BasicProgramming2 pull request #11
Opened 2020-03-20 14:06 UTC by EmirVildanov

2020-04-06 12:44 UTC, SpirinEgor requested changes

2020-04-06 12:44 UTC, SpirinEgor commented on src/main/kotlin/testFirst/taskOne/PriorityQueue.kt
> +            }
```
return sign(this.priorityValue - other.priorityValue)
```

2020-04-06 12:44 UTC, SpirinEgor commented on src/main/kotlin/testFirst/taskOne/PriorityQueue.kt
> +            val value = element!!.value
Не надо использовать `!!`

2020-04-06 12:44 UTC, SpirinEgor commented on src/main/kotlin/testFirst/taskOne/AVLTree.kt
> +    private fun rotateRight(pair: Pair<K, V>?): Pair<K, V>? {
Очень похожа на левый поворот, можно объединить в одну

2020-04-06 12:44 UTC, SpirinEgor commented on src/main/kotlin/testFirst/taskOne/AVLTree.kt
> +            size
Что делает просто `size`?

2020-04-20 15:03 UTC, EmirVildanov commented on src/main/kotlin/testFirst/taskOne/AVLTree.kt
> +    private fun rotateRight(pair: Pair<K, V>?): Pair<K, V>? {
Привет. Я ищу, что можно с этим сделать. Хочется так, чтобы передать в функцию аргумеyт вроде rotate(side) и чтобы он автоматически вставал на место pair.side, где side - либо rightChild, либо leftChild. Не могу понять, как типизировать этот аргумент функции. Можешь подсказать?

2020-06-08 06:46 UTC, closed without merging