Task4.1
EmirVildanov/BasicProgramming2 pull request #12
Opened 2020-04-20 17:52 UTC by EmirVildanov

2020-06-07 15:48 UTC, elena-lyulina requested changes

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Main.kt
> +    println(table.words.contains("file"))
> Общение с пользователем должно происходит в интерактивном режиме

Надо считывать от пользователя команды типа "добавить значение x в таблицу", "напечатать статистику" и делать эти действия до тех пор, пока не будет введена команда "exit"

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Test
> +Some words from my friendo text file
Клади такие файлы в ресурсы, пожалуйста
Это специальная папка resources в src/main (рядом с папкой kotlin), по идее тебе сама среда при создании новой папки предложит создать папку resources и заодно пометит ее как папку с ресусрами. В этой папке и надо хранить все файлы, причем в соответствии с тем, где ты их используешь. Если ты text.txt используешь в src/main/kotlin/folder1/folder2/main.kt, то хранить его надо в src/main/resources/folder1/folder2/text.txt, соблюдая ту же систему подпапок. Для тестов ресурсы так же устроны, это тоже отдельная папка.

И еще указывай у них раширение, txt отлично подойдет

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +const val LOAD_FACTOR_MAXIMUM = 0.9
Константы, относящиеся к хэш-таблице, лучше хранить в самом классе в качестве полей. Зачем их делать глобальными?

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +    }
Лучше реализовать отдельный интерфейс для хэш-функций, а сами хэшфункции делать классами, наследующимися от этого интерфейса. Так и константы для них удобнее хранить (они тогда будут полями к соответствующему классу), и пользоваться ими будет удобнее

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +    }
классы просто для хранения данных в их полях лучше реализовывать через [data class](https://kotlinlang.org/docs/reference/data-classes.html)

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +            }
можно сделать чуть проще и чуть более kotlin style:
`bucketsArray.map { it.conflictsNumber }.max()`

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +            2 -> this.hashFunction = ::secondHashFunction
А если сюда какое-то другое число передали? И вообще лучше конечно обращаться к фцнкции по имени, а то 1 и 2 не очень репрезентативно. Когда сделаешь для них классы, заведи поле 'name' с каким-нибудь адекватными именем (не first и second), описывающем саму функцию. Давать правильные имена -- очень важно, так как через пару неделб ты уже забудешь, что за первая функция, что за вторая. Нормальные имена помогут быстро вспомнить

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +        loadFactor = words.size.toDouble() / bucketsArray.size.toDouble()
Можно только одно из значений перевести в Double
И ты loadFactor считаешь в нескольких местах, что плохо, так как ты в одном из мест можешь ошибиться. В таком случае обычно код выносят в отдельную функцию.

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +        }
прелесть хэш-таблицы еще и в том, что при удалении слова не надо пробегаться по всем бакетам. Достаточно найти тот, у которого хэш такой же как у удаляемого элемента

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +        bucketsArray[hashIndex].words.add(currentWord)
А если в этой ячейке уже было такое же слово?

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +    val words = mutableSetOf<String>()
Ох, зачем же ты хранишь два раза все слова-то? И в bucketsArray, и в words? Так же по памяти в два раза больше получается!
Тем более ты words используешь практически только для получения количества слов, сделай, пожалуйста, просто поле для количества слов и обновляй его при добавлении/удалении, не надо два раза хранить ничего

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +    }
[Можно](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-list.html) сразу при инициализации заполнить список элементами:
MutableList( number_of_buckets ) { Bucket() }

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +    var expansionNumber: Int = 0
Давай без публичных полей. У тебя например сейчас можно просто обратиться к words и добавить туда какое-нибудь слово со стороны, оно тебе надо? Если хочешь дать пользователю какой-то доступ к ним, то реализуй соответствующие функции. Например, если хочешь, чтобы он мог проверять, что в words содержатся какие-то слова, то сделай такую функцию в классе и пусть пользователь ее вызывает. 

Или например кто-то левый поменяет тебе хэш-функцию незаметно (она же публичная!), а таблица при этом не перестроится. Проблема. 

Так что не надо публичных полей, это прямо оочень опасно

2020-06-07 15:48 UTC, elena-lyulina commented on src/test/kotlin/homework/hw4/task1/HashtableTest.kt
> +        hashtable.addFromFile(File("src/test/kotlin/homework/hw4/task1/testFileThatWillMakeHashtableToExtand"))
Ты эти пути по несколько раз используешь в тестах, их лучше вынести в поля класса, чтобы не ошибиться при наборе в очередной раз

2020-06-07 15:48 UTC, elena-lyulina commented on src/test/kotlin/homework/hw4/task1/HashtableTest.kt
> +}
Проверь еще пожалуйста, что при изменени хэш-функции у тебя те же элементы остаются в таблице, и что все ок при попытке удалить несуществующий элемент

2020-06-07 15:48 UTC, elena-lyulina commented on src/main/kotlin/homework/hw4/task1/Hashtable.kt
> +}
По условию задачи надо еще добавить поиск значения в хеш-таблице.

2020-11-28 19:04 UTC, SpirinEgor approved these changes

2020-11-29 16:14 UTC, merged