Created treeReader project
EmirVildanov/BasicProgramming2 pull request #8
Opened 2020-03-16 16:32 UTC by EmirVildanov

2020-11-28 19:21 UTC, SpirinEgor requested changes

2020-11-28 19:21 UTC, SpirinEgor commented on src/main/kotlin/homework/hw4/task2/TreeReader.kt
> +        }
Уверен, что можно и аккуратнее записать :)

2020-11-28 19:21 UTC, SpirinEgor commented on src/main/kotlin/homework/hw4/task2/Operator.kt
> +        }
Хмм, а зачем знать про устройство ребёнка? Чтобы лишние скобочки случайно не поставить? Кажется, что в таком случае лучше взять текстовое представление ребёнка и с ним что-то поделать

2020-11-28 19:21 UTC, SpirinEgor commented on src/main/kotlin/homework/hw4/task2/Operator.kt
> +        }
А вообще, пусть операнды просто значение возвращают, а операторы в скобки оборачивают. Тогда вообще никаких проверок не будет

2020-11-30 14:28 UTC, SpirinEgor requested changes

2020-11-30 14:28 UTC, SpirinEgor commented on src/main/kotlin/homework/hw4/task2/Operator.kt
> +        return stringTree
Ну если исправлять, то уж нормально
```
return "($operandString $leftChild $rightChild)"
```

2020-11-30 14:39 UTC, EmirVildanov commented on src/main/kotlin/homework/hw4/task2/Operator.kt
> +        return stringTree
Да, тупо, согласен. Привык полагатья на идейку в этом плане...

2020-11-30 14:50 UTC, SpirinEgor approved these changes

2020-11-30 14:57 UTC, merged